import { Category, Country, Lang } from "../logic/types";

export const categories: Category[] = [
  "general",
  "business",
  "entertainment",
  "sport",
  "health",
  "science",
  "mercury",
  "venus",
  "earth",
  "mars",
  "jupiter",
  "saturn",
  "uranus",
  "neptune",
  "pluto"
];

export const countryLang: { [key in Country]: Lang } = {
  gb: "en",
  us: "en",
  de: "de",
  nl: "nl",
  pl: "pl",
};

export const queries: { [key in Lang]: { [key in Category]: string } } = {
  en: {
    general: "news today",
    business: "business today",
    entertainment: "entertainment today",
    sport: "sport today",
    health: "health",
    science: "science today",
    mercury: "planet mercury",
    venus: "planet venus",
    earth: "planet earth",
    mars: "planet mars",
    jupiter: "planet jupiter",
    saturn: "planet saturn",
    uranus: "planet uranus",
    neptune: "planet neptune",
    pluto: "planet pluto",
  },
  de: {
    general: "nachrichten",
    business: "unternehmen",
    entertainment: "unterhaltung",
    sport: "sport",
    health: "gesundheit",
    science: "wissenschaft",
    mercury: "planet merkur",
    venus: "planet venus",
    earth: "planet erde",
    mars: "planet mars",
    jupiter: "planet jupiter",
    saturn: "planet saturn",
    uranus: "planet uranus",
    neptune: "planet neptun",
    pluto: "planet pluto",
  },
  nl: {
    general: "nieuws",
    business: "ondernemen",
    entertainment: "entertainment nieuws",
    sport: "sport nieuws",
    health: "gezondheid",
    science: "wetenschap",
    mercury: "planet mercurius",
    venus: "planeet venus",
    earth: "planeet aarde",
    mars: "planeet mars",
    jupiter: "planeet jupiter",
    saturn: "planeet saturnus",
    uranus: "planeet uranus",
    neptune: "planeet neptunus",
    pluto: "planeet pluto",
  },
  pl: {
    general: "wiadomosci",
    business: "biznes",
    entertainment: "rozrywka",
    sport: "sport wiadomosci",
    health: "zdrowie",
    science: "nauka",
    mercury: "planeta merkury",
    venus: "planeta wenus",
    earth: "planeta ziemia",
    mars: "planeta mars",
    jupiter: "planeta jowisz",
    saturn: "planeta saturn",
    uranus: "planeta uran",
    neptune: "planeta neptun",
    pluto: "planeta pluton",
  },
};
